#!/bin/bash

# ARIX.help - Database Setup Guide
# This script shows you how to set up the database

echo "======================================"
echo "ARIX.help - Complete Setup Guide"
echo "======================================"
echo ""
echo "Step 1: Run the Database Schema"
echo "=================================="
echo ""
echo "IMPORTANT: Before the chat works, you MUST run the database schema."
echo ""
echo "Option A: Using Supabase SQL Editor (Recommended)"
echo "---------------------------------------------------"
echo "1. Go to https://app.supabase.com"
echo "2. Select your project"
echo "3. Go to SQL Editor (left sidebar)"
echo "4. Click 'New Query'"
echo "5. Copy entire contents of: lib/db/schema.sql"
echo "6. Paste into the editor"
echo "7. Click 'RUN' button"
echo ""
echo "Option B: Using Supabase CLI"
echo "-----------------------------"
echo "supabase db push"
echo ""
echo "Option C: Using API (automatic on first chat)"
echo "----------------------------------------------"
echo "POST /api/init"
echo "This will create the user profile automatically"
echo ""
echo ""
echo "Step 2: Start the Development Server"
echo "====================================="
echo "pnpm dev"
echo ""
echo "Step 3: Test the Chat"
echo "===================="
echo "1. Navigate to http://localhost:3000/chat"
echo "2. Login or create an account"
echo "3. Click 'New Chat'"
echo "4. Type a message"
echo "5. Hit send"
echo ""
echo "Verify:"
echo "✓ User message appears immediately"
echo "✓ AI response streams in"
echo "✓ After refresh, history persists"
echo "✓ Conversation title auto-generated"
echo ""
echo ""
echo "Step 4: Common Issues"
echo "===================="
echo ""
echo "Issue: 'Conversation not found' error"
echo "Fix: Run the database schema first"
echo ""
echo "Issue: Messages not saving"
echo "Fix: Verify RLS policies by checking Supabase dashboard"
echo ""
echo "Issue: User profile error"
echo "Fix: POST /api/init to create profile"
echo ""
echo ""
echo "Setup Complete!"
echo "================"
echo "Your chat should now be fully functional!"
